config/routes.rb
Buyroch::Application.routes.draw do
  get "properties/show"
  get "users/index"
  get "users/show"
  get "offices/show"
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get "searches/properties"
  get "searches/unique_spaces"
  get "home/index"
  get "home/about"
  get "home/commercial"
  get "myproperties" => 'properties#myproperties'
  post "autopost/loopnet"
  post "autopost/mncar"
  post "autopost/craigslist"

 root 'home#index'
 resource :search

 resource :office

 resources :properties

  devise_scope :user do
         get 'cucumber_signout' => 'devise/sessions#destroy'
    end

  

 resources :properties do
  member do
    post 'loopnet'
    post 'mncar'
    post 'craigslist'
  end
 end

namespace :api, :defaults => {:format => :json} do
  namespace :v1 do
    resources :properties
  end
end

end

app/models/property.rb
require 'loopnet.rb'
class Property < ActiveRecord::Base
  validates :title, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true
  validates :photo_file_name, :presence => true
  has_attached_file :photo, :styles => { :medium => "400x400>", :thumb => "100x100>", :map => "50X50"}, :default_url => "/images/:style/missing.png"	
  has_many :attachments, as: :attachable
  geocoded_by :address
  after_validation :geocode
  belongs_to :user

  accepts_nested_attributes_for :attachments, :allow_destroy => true

  def loopnet(login,pwd)
  	session = Loopnet.new(login,pwd)
  	session.login
  	page = session.addsale(self)
  	return "http://www.loopnet.com/xNet/MainSite/User/Home/MyListings.aspx?LinkCode=29390"
  end


end

app/controllers/api/properties_controller.rb
class API::V1::PropertiesController < ApplicationController

  def index
    @properties = Property.all
    respond_to do |format|
      format.json { render :json => @properties}
    end
  end

end

app/controllers/api/v1/properties_controller.rb
class API::V1::PropertiesController < ApplicationController
before_filter :cors_preflight_check
after_filter :cors_set_access_control_headers

# For all responses in this controller, return the CORS access control headers.

def cors_set_access_control_headers
  headers['Access-Control-Allow-Origin'] = '*'
  headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
  headers['Access-Control-Max-Age'] = "1728000"
end

# If this is a preflight OPTIONS request, then short-circuit the
# request, return only the necessary headers and return an empty
# text/plain.

def cors_preflight_check
  if request.method == :options
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
    headers['Access-Control-Max-Age'] = '1728000'
    render :text => '', :content_type => 'text/plain'
  end
end


  def index
  	if params[:query]
    ss = "%#{params[:query]}%"
  	  @properties = Property.where("published = true and (unique_space != true or unique_space IS NULL)  and (address LIKE ? or title LIKE ? or description LIKE ?)",ss,ss,ss)
    elsif params[:agent]
      agent = params[:agent]
      @properties = Property.joins(:user).where("(properties.unique_space != true or properties.unique_space IS NULL) and properties.published = true and users.email = ?",agent)
    else
      @properties = Property.where("(properties.unique_space != true or properties.unique_space IS NULL) and published = true")
    end
    
    respond_to do |format|
      format.json { render :json => @properties}
    end
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def loopnet
      @property = Property.find(params[:id])
      @id = params[:id]
      @status = @property.loopnet(current_user.loopnet_logon,current_user.loopnet_password)
      #redirect_to {:action => :show}
  end

  def show
  	@property = Property.find(params[:id])
    
    @hash = Gmaps4rails.build_markers(@property) do |place, marker|
         marker.lat place.latitude
         marker.lng place.longitude
     end
     
  end

  def new
     @property = Property.new
  end

  def create
 
      @property = Property.new(property_params)
      @property.user_id = current_user.id
      Rails.logger.info("###DEBUG current_user     :=> #{current_user}")
      Rails.logger.info("###DEBUG property.user_id :=> #{@property.user_id}")
        respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        Rails.logger.info(@property.errors.inspect)
        format.html { render action: 'new' }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end   
     
 end


  def update
    property = Property.find(params[:id])
    property.update_attributes!(property_params)
    redirect_to property
  end

  def myproperties
    @properties = Property.all()
  end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def property_params
  params.require(:property).permit(:photo, :title, :description, :price, :address)
end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_list.html.erb
			<div class='row'>
				<div id='siteMain' class='large-12 small-12 columns'>


				
				<div class='content mb22 mt22'>
								</div>

				<div class='property-list'>
<% @properties.each do |p| %>
<!-- PROPERTY -->
					<div class="property type-property status-publish hentry layout-property-list">

	<div class='row'>
					<div class='large-6 small-12 columns'>
				<div class='post-image'>
					<a href='/properties/<%=p.id.to_s%>' class='hoverlink hide-for-small'>
						<img width="284" height="188" src=" <%= p.photo.url(:medium)%>" class="attachment-est_card wp-post-image" alt="r1" />					</a>
					<a href='/properties/<%=p.id.to_s%>' class='hoverlink show-for-small mb11'>
						<img width="627" height="188" src=" <%= p.photo.url(:medium)%>" class="attachment-est_card_wide wp-post-image" alt="r1" />					</a>
				</div>
			</div>
		
		<div class='large-6 small-12 columns'>
			<hgroup>
				<h1><a href='/properties/<%=p.id.to_s%>'><%=p.title%></a></h1>
									<h2 class='light'><span class="est_value city-r"><span class="value">rochester</span></span>, <span class="est_value state-M"><span class="value">Minnesota</span></span></h2>
							</hgroup>

				<table class="detail-table ">
		<tbody>
			</tbody>
	</table>
	
		</div>

	</div>


</div>
<% end %>
<!-- END PROPERTY -->


</div><div class="pagination"></div>					</div>
				</div>
							</div>
		

app/views/properties/_search_form.html.erb
<div id='searchContainer'>
  <form id='map-page-form' class="custom form-search" action="/searches/<%=@searchtype%>" method="GET">
  <div id='main-search'>
    <input type='submit' class='submit-search button-search' value='GO!'>
    <input type="text" name="query" class='main-search-field' value="<%= params[:query]%>" placeholder='Location, Options, Keywords?'>  </div>
				<div id='advanced-search' style="display:none">

					
					<div class='row form-row' >
						<div class='large-4 small-12 columns'>
														<label for="$detail" class='offset'>Distance</label>
						</div>

						<div class='large-8 small-12 columns' >
													    <select id="radiusSelect">
													     </select>
						</div>
					</div>

						
							
	<div class='estSearch vertical_twocol'>
			<div class='row form-row'>
			<div class='large-4 small-12 columns'>
				<label for="_est_meta_property_area" class='offset'>
					Property Area				</label>
			</div>
			<div class='large-8 small-12 columns'>
						
			<select id="_est_meta_property_area" class="medium" name='_est_meta_property_area'>
				<option value="">Any</option><option  value="5000">5.000 acres</option><option  value="54,443">54 acres</option>			</select>

						</div>
		</div>
				<div class='row form-row'>
			<div class='large-4 small-12 columns'>
				<label for="_est_meta_price" class='offset'>
					Price				</label>
			</div>
			<div class='large-8 small-12 columns'>
					<p data-id='_est_meta_price' class='mb0 range-values'><span class='min'><span class="est_value price-1"><span class="unit">$</span><span class="value">1.500.000</span></span></span> - <span class='max'><span class="est_value price-1"><span class="unit">$</span><span class="value">1.500.000</span></span></span></p>
	<div class='range-container'>
	<div id='_est_meta_price' class='range on' data-name='_est_meta_price' data-min="1500000" data-max='1500000' data-value_min='' data-value_max=''></div>
	</div>
			</div>
		</div>
				<div class='row form-row'>
			<div class='large-4 small-12 columns'>
				<label for="property_category" class='offset'>
					Property Categories				</label>
			</div>
			<div class='large-8 small-12 columns'>
									<select id="property_category" class="medium" name='property_category'>
				<option value="">All</option> <option  value="2">Commercial</option>			</select>
						</div>
		</div>
				<div class='row form-row'>
			<div class='large-4 small-12 columns'>
				<label for="property_type" class='offset'>
					Property Types				</label>
			</div>
			<div class='large-8 small-12 columns'>
									<select id="property_type" class="medium" name='property_type'>
				<option value="">All</option> <option  value="3">Rental Space</option>			</select>
						</div>
		</div>
			</div>
	

						

				</div>


				<div class='row'>
					<div class='large-12 small-12 columns'>
						<span id='advanced-search-switch' data-open_text='Minimized Search' data-closed_text='Advanced Search' style='display:none'>
							Advanced Search						</span>
					</div>
				</div>
  </form>
</div>

<script type="javascript">
$(function() {
  $('span#advanced-search-switch').click({
    $('div#advanced-search').toggle();
  });
}); 
</script>

app/views/properties/_searchresults.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div id='estatementMapContainer' style='height:500px'>
<div id="map" class='map no-full' style='height:700px'></div>
 
  <%=render "/properties/search_form"%>
</div>

<% @properties.each do |p| %>

  <div class='row'><div class='small-12 large-12 columns'><div id="featured-properties-container"><div id="featured-flag"></div><div id="featured-properties" data-speed="10">

<!-- Property -->
    <div class="property type-property status-publish hentry layout-property-flyer" style="background-image: url( <%= p.photo.url(:medium)%> )">
  <div class='post-content'>
    <div class='post-image-overlay'></div>
    <h1><a class='heading-text-color' href='/properties/<%=p.id.to_s%>'><%=p.title%></a></h1>
    <div class='content'>
      <p><%=p.description.truncate(310, :separator => ' ')%></p>
    </div>
    <div class='details'>
      <div class="info light">
      <span class="est_value building_area-1"><span class="value"><%=p.sqrft%></span><span class="unit"> sqft</span></span> </div>
      <a class='button small' href='/properties/<%=p.id.to_s%>'>details</a>

    </div>
  </div>

</div>      
<!--end property-->     
  </div></div></div>  </div>
  <p><br /></p>
  <% end %>

  <script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);
});
</script>

app/views/properties/loopnet.html.erb
<a href="<%=@status%>" target="new">Loopnet</a>

app/views/properties/myproperties.html.erb
					
						
		
<div class='row mt44'>
	<div class='large-12 small-12 columns'>
		<div id='siteContent'>

			<div class="page-title"><div class="section-title"><span class="flag"><img class='retina' width='18' height='18' src='<%=asset_path "home.png"%>' alt='Icon'></span><h2>Let&#8217;s Sell Some Properties</h2></div></div>
<%= link_to 'Add New Property', new_property_path %>	
<%= render "properties/list" %>
</div>
	</div>
</div>

app/views/properties/new.html.erb
<div class='row mt44'>
	<div class='large-12 small-12 columns'>
		<div id='siteContent'>
			<div class='row'>
				<div id='siteMain' class='large-12 small-12 columns'>

					<div class="content" >
					
<%= form_for @property, url: {action: "create"}, html: {class: "form-horizontal",  multipart: true} do |f| %>
<label class="control-label" for="title">Title</label>
  <%= f.text_field :title %>
  <label class="control-label" for="description">Description</label>
  <%= f.text_area :description, size: "60x6" %>
  <label class="control-label" for="photo">Photo</label>
  <%= f.file_field :photo %>
  <label class="control-label" for="price">Price</label>
  <%= f.number_field :price %>
  <label class="control-label" for="address">Address</label>
  <%= f.text_field :address %>
  <%= f.submit "Create" %>
<% end %>

	
					</div>				</div>
							</div>

		</div>
	</div>
</div>

app/views/properties/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script>
$(document).ready(function(){
  $('.bxslider').bxSlider();
});
</script>

<div class='row mt44'>
	<div class='large-12 small-12 columns'>
		<div id='siteContent'>

			<div class='row'>

				<div class='columns large-12 small-12 mb22'>
					<div class="page-title">
						<div class="section-title"><span class="flag"><img class='retina' width='18' height='18' src='<%=asset_path "home.png"%>' alt='Icon'/></span><h2><%=@property.title%></h2>
						<p><%=@property.address%></p>
						</div>						
					</div>
				
				</div>
								<div id='propertyPrintButton'>
								<a href="http://www.printfriendly.com" style="color:#6D9F00;text-decoration:none;" class="printfriendly" onclick="window.print();return false;" title="Printer Friendly and PDF"><img style="border:none;" src="http://cdn.printfriendly.com/button-print-gry20.png" alt="Print Friendly and PDF"/></a>
				               </div>
			
<div style="float:right;width:32%;margin:.5%">		

	<div id='siteSidebar'> <!-- class='small-12 large-4 columns ' >-->
		<div class="widget-container"><div id="bshagentcontactwidget-2" class="widget widget_bshagentcontactwidget">
		<div class="agent-title">
		<h1 class="widget-title">Property Agent</h1>
		</div>
		<header>
		<img alt='' src='<%=@property.user.avatar.url(:thumb)%>' class='avatar avatar-80 photo' height='80' width='80' />
		<div class="agent-details">
		<h1 class="agent-name"><a href="/"><%=@property.user.name%></a></h1>
		<div class="agent-position"><%=@property.user.title%></div></div>
<div class="social"><a class="twitter socialIcon" href="http://twitter.com/<%=@property.user.twitter_name%>"></a><a class="facebook socialIcon" href="<%=@property.user.facebook_url%>"></a><a class="linkedin socialIcon" href="<%=@property.user.linked_in_url%>"></a></div>
		</header>

		<ul class="contact m22"><li class="phoneNumber"><span class="icon"><img alt="Phone Icon" src="<%=asset_path 'iphone.png'%>"></span> <a><%=@property.user.phone%></a></li>
		<li class="email">
		<span class="icon"><img alt="Envelope Icon" src="<%=asset_path 'envelope.png'%>"></span> 
		<a href="mailto:<%=@property.user.email%>"><%=@property.user.email%></a>
		</li></ul>
		
		

		

		<div class="end"></div></div></div>

		<div class="widget-container"><div id="bshmapwidget-3" class="widget widget_bshmapwidget"><h1 class="widget-title">Property Map</h1>			
			

	<div id="map" class='map-canvas' style='width:100%;height:250px'></div>
	


	<div class="end"></div></div></div><div class="widget-container"><div id="bshpropertycontactwidget-2" class="widget widget_bshpropertycontactwidget">

		<div class="end"></div></div></div>				</div></div>	
<div style="float:left;width:65%">
		<div id='siteMain' ><!-- ='large-8 small-12 columns'>-->
			<div class="property type-property status-publish hentry layout-property">

			
			<div id='post-slider'>
<!--		<div id="property-slider" class="flexslider">
			<ul>
									<li>
						<img src="<%=@property.photo.url%>" title='r1' alt='r1' />
					</li>
					<li>
						<img src="<%=@property
.photo.url%>" title='r1' alt='r1' />
					</li>
					<li>
						<img src="<%=@property
.photo.url%>" title='r1' alt='r1' />
					</li>
							</ul>
		       </div> -->

				<div> <!--id="property-carousel" class="flexslider carousel">-->
			<ul class="bxslider">
			<img src="<%=@property.photo.url%>" title='r1' alt='r1' />
			<%@property.attachments.each do |attached| %>
									<li>
						<img src="<%=attached.picture.url%>" title='r1' />
					</li><%end%>
								
							</ul>
		     </div>
		</div>

<div class='content'>

<div>
<p>
Square Footage: <%=@property.sqrft%> sqft - 
<%if @property.lease%>
Price per sqft:
<%else%>
Asking Price:  
<%end%>
 $<%=@property.price%> 
<%if @property.unique_space%>
 per <%=@property.price_unit%>
<%end%>
</p>
<h3>Description</h3>
<p><%=@property.description%></p>


</div>
</div>
</div>	

</div>	
</div>

			</div>
		</div>
	</div>
</div> 

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);
});
</script>

<script>
var pfHeaderImgUrl = '';
var pfHeaderTagline = '';
var pfdisableClickToDel = 0;
var pfHideImages = 0;
var pfImageDisplayStyle = 'block';
var pfDisablePDF = 0;
var pfDisableEmail = 0;
var pfDisablePrint = 0;
var pfCustomCSS = '';
var pfBtVersion='1';
(function(){
	var js, pf;
	pf = document.createElement('script');
	pf.type = 'text/javascript';
	if('https:' == document.location.protocol){js='https://pf-cdn.printfriendly.com/ssl/main.js'}
		else
			{js='http://cdn.printfriendly.com/printfriendly.js'};
	pf.src=js;
	document.getElementsByTagName('head')[0].appendChild(pf)
});
</script>

app/views/properties/show_bootstrap_html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="container-fluid">
  <div class="row">
   <div class="col-md-9">
<div class="section-title"><span class="flag"><img class='retina' width='18' height='18' src='<%=asset_path "home.png"%>' alt='Icon'></span><h2><%=@property.title%></h2></div>						
<div id='propertyPrintButton'>							
<script>var pfHeaderImgUrl = '';var pfHeaderTagline = '';var pfdisableClickToDel = 0;var pfHideImages = 0;var pfImageDisplayStyle = 'block';var pfDisablePDF = 0;var pfDisableEmail = 0;var pfDisablePrint = 0;var pfCustomCSS = '';var pfBtVersion='1';(function(){var js, pf;pf = document.createElement('script');pf.type = 'text/javascript';if('https:' == document.location.protocol){js='https://pf-cdn.printfriendly.com/ssl/main.js'}else{js='http://cdn.printfriendly.com/printfriendly.js'}pf.src=js;document.getElementsByTagName('head')[0].appendChild(pf)})();</script>								
<a href="http://www.printfriendly.com" style="color:#6D9F00;text-decoration:none;" class="printfriendly" onclick="window.print();return false;" title="Printer Friendly and PDF"><img style="border:none;" src="http://cdn.printfriendly.com/button-print-gry20.png" alt="Print Friendly and PDF"/></a>				</div>
				


			
<img src="<%=@property.photo.url%>" title='r1' alt='r1' />

	

		
			<div class="row">
			<% @property.attachments.each do |attached| %>
									<div class="col-md-4">
						<img src="<%=attached.picture.url(:medium)%>" title='r1' />
					</div><%end%>
								
							</div>
		
<h3>Highlights</h3>
<ul>
<li><img alt="" src="http://s.lnimg.com/images/profile/transparentArrow.gif" /></li>
</ul>

<h3>Description</h3>
<p><%=@property.description%></p>
</div>		
<div class="col-md-3">
				<div id='siteSidebar' class='small-12 large-4 columns ' style ="margin-top: -500px">
					<div class="widget-container"><div id="bshagentcontactwidget-2" class="widget widget_bshagentcontactwidget"><div class="agent-title"><h1 class="widget-title">Property Agent</h1></div><header><img alt='' src='<%=@property.user.avatar.url(:thumb)%>' class='avatar avatar-80 photo' height='80' width='80' /><div class="agent-details"><h1 class="agent-name"><a href="/"><%=@property.user.name%></a></h1><div class="agent-position">RGI - Commercial Realtor</div><ul class="contact m22"><li class="phoneNumber"><span class="icon"><img alt="Phone Icon" src="<%=asset_path 'iphone.png'%>"></span> <a href="tel:(507)951-7130">(507) 951-7130</a></li><li class="email"><span class="icon"><img alt="Envelope Icon" src="<%=asset_path 'envelope.png'%>"></span> <a href="mailto:<%=@property.user.email%>"><%=@property.user.email%></a></li></ul></div></header><div class="social"><a class="twitter socialIcon" href="http://twitter.com/buckybeeman"></a><a class="facebook socialIcon" href="https://www.facebook.com/buckybeeman"></a></div><div class="end"></div></div></div><div class="widget-container"><div id="bshmapwidget-3" class="widget widget_bshmapwidget"><h1 class="widget-title">Property Map</h1>


	<div id="map" class='map-canvas' style='width:100%;height:250px'></div>
	
</div>
</div>
</div>

	

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);
});
</script>